blog_template:
    resource: "@BLOGTemplateBundle/Resources/config/routing.yml"
    prefix:   /	
login:
    pattern:   /login
    defaults:  { _controller: BLOGUserBundle:Security:login }
login_check:
    pattern:   /login_check

logout:
    pattern:   /logout