blog_template_homepage:
    path:     /index
    defaults: { _controller: BLOGTemplateBundle:Page:index }

blog_template_homepage2:
    path:     /
    defaults: { _controller: BLOGTemplateBundle:Page:index }

blog_template_dprint:
    path:     /dprint
    defaults: { _controller: BLOGTemplateBundle:Page:dprint }

blog_template_about:
    path:     /about
    defaults: { _controller: BLOGTemplateBundle:Page:about }

blog_template_contact:
    path:     /contact
    defaults: { _controller: BLOGTemplateBundle:Page:contact }

blog_template_test:
    path:     /page_test
    defaults: { _controller: BLOGTemplateBundle:Page:page_test }

blog_template_add:
    path:     /add
    defaults: { _controller: BLOGTemplateBundle:Page:add }

blog_template_view:
    path:     /view/{id}
    defaults: { _controller: BLOGTemplateBundle:Page:view }

blog_template_delete:
    path:     /delete/{id}
    defaults: { _controller: BLOGTemplateBundle:Page:delete }


blog_template_edit:
    path:     /edit/{id}
    defaults: { _controller: BLOGTemplateBundle:Page:edit }
